name: isxportfolio
description: ISX Portfolio Management Application

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  http: ^1.1.2
  fl_chart: ^0.70.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
