version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    env_file:
      - backend/.env
    environment:
      - GIN_MODE=release

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  sqlite_data:
    driver: local 